### ISSUE TITLE
Get an indexError sometimes.

### ISSUE THREAD

**Issue by shivamvats** [kshitij10496/goodquotes#1]
```
(python3.6) 12:32:26 ~$ goodquotes
Traceback (most recent call last):
  File "/home/aries/envs/python3.6/bin/goodquotes", line 11, in <module>
    sys.exit(cli())
  File "/home/aries/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/aries/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/aries/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aries/envs/python3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/aries/envs/python3.6/lib/python3.6/site-packages/goodquotes/cli.py", line 27, in cli
    quote_book(None)
  File "/home/aries/envs/python3.6/lib/python3.6/site-packages/goodquotes/cli.py", line 40, in quote_book
    rquote = random_quote(selected_title, selected_author)
  File "/home/aries/envs/python3.6/lib/python3.6/site-packages/goodquotes/logic.py", line 21, in random_quote
    random_quote = random.choice(book_quotes)
  File "/home/aries/envs/python3.6/lib/python3.6/random.py", line 257, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```

**Comment by kshitij10496** [comment]
Thanks for pointing this out.

Specifically, in this case, the `book_quotes` object can be `None` but it is supposed to an iterable; thus, the `IndexError`.

Speaking generally, I think the major issue with the application is the part of scraping the HTML response from Goodreads. Since I couldn't find a free Quotes API at that time (and found WikiQuote to be a headache to scrape), I settled for Goodreads. Do you happen to know any other API service that can be used instead?

This application needs refactoring.

**Comment by shivamvats** [comment]
Your humble user knows nothing about scraping or HTML.

**Comment by kshitij10496** [comment]
Fixed in v1.0.1 😃 

Can you update your install and let me know if it works?

**Comment by shivamvats** [comment]
Thanks! Looks like it's improved. It did fail once though.

**Comment by kshitij10496** [comment]
> It did fail once though.

Can you share the command which resulted in the failure?
